(function(){
const initialStudy="";
const initialPrior="";
const els={status:document.getElementById('status'),series:document.getElementById('seriesList'),grid:document.getElementById('grid'),meta:document.getElementById('meta'),vmeta:document.getElementById('viewportMeta'),prev:document.getElementById('prev'),next:document.getElementById('next'),layout:document.getElementById('layout'),priorInput:document.getElementById('priorInput'),priorLoad:document.getElementById('priorLoad'),compare:document.getElementById('compare'),notes:document.getElementById('notes'),notesSave:document.getElementById('notesSave'),notesLoad:document.getElementById('notesLoad'),notesClear:document.getElementById('notesClear'),notesStatus:document.getElementById('notesStatus'),reset:document.getElementById('reset')};
const tools=[].slice.call(document.querySelectorAll('.tool'));
const st={studies:{},order:[],viewports:[],active:0,layout:1,tool:'Wwwc',primary:initialStudy||'',prior:initialPrior||''};
function msg(t){els.status.textContent=t}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function setup(){
 if(typeof cornerstone==='undefined'||typeof cornerstoneTools==='undefined'||typeof cornerstoneWADOImageLoader==='undefined'||typeof dicomParser==='undefined'||typeof cornerstoneMath==='undefined'){msg('Viewer libraries failed to load');return false}
 cornerstoneWADOImageLoader.external.cornerstone=cornerstone;cornerstoneWADOImageLoader.external.dicomParser=dicomParser;cornerstoneTools.external.cornerstone=cornerstone;cornerstoneTools.external.cornerstoneMath=cornerstoneMath;
 cornerstoneTools.init({mouseEnabled:true,touchEnabled:true,globalToolSyncEnabled:false,showSVGCursors:true});
 [['WwwcTool','Wwwc'],['PanTool','Pan'],['ZoomTool','Zoom'],['LengthTool','Length'],['RectangleRoiTool','RectangleRoi'],['ArrowAnnotateTool','ArrowAnnotate'],['StackScrollMouseWheelTool','StackScrollMouseWheel']].forEach(function(d){if(typeof cornerstoneTools[d[0]]!=='undefined'){cornerstoneTools.addTool(cornerstoneTools[d[0]])}});
 try{cornerstoneTools.setToolActive('StackScrollMouseWheel',{})}catch(e){}
 setTool('Wwwc');
 return true;
}
function setTool(name){st.tool=name;['Wwwc','Pan','Zoom','Length','RectangleRoi','ArrowAnnotate'].forEach(function(t){try{cornerstoneTools.setToolPassive(t)}catch(e){}});try{cornerstoneTools.setToolActive(name,{mouseButtonMask:1})}catch(e){msg('Tool not available: '+name)};tools.forEach(function(b){b.classList.toggle('active',b.dataset.tool===name)})}
function applyLayout(v){st.layout=Number(v)||1;els.grid.innerHTML='';st.viewports=[];if(st.layout===1){els.grid.style.gridTemplateColumns='1fr';els.grid.style.gridTemplateRows='1fr'}else if(st.layout===2){els.grid.style.gridTemplateColumns='1fr 1fr';els.grid.style.gridTemplateRows='1fr'}else{els.grid.style.gridTemplateColumns='1fr 1fr';els.grid.style.gridTemplateRows='1fr 1fr'}
 for(let i=0;i<st.layout;i++){const vp=document.createElement('div');vp.className='vp';vp.tabIndex=0;const ov=document.createElement('div');ov.className='ov';ov.innerHTML='<span>Viewport '+(i+1)+'</span><span>-</span>';vp.appendChild(ov);vp.addEventListener('click',function(){setActive(i)});vp.addEventListener('cornerstoneimagerendered',function(e){overlay(i,e.detail.viewport)});els.grid.appendChild(vp);cornerstone.enable(vp);cornerstoneTools.addStackStateManager(vp,['stack']);st.viewports.push({el:vp,ov:ov,stack:null,study:null,uid:null,label:null})}
 setActive(0);
}
function setActive(i){st.active=i;st.viewports.forEach(function(v,idx){v.el.classList.toggle('active',idx===i)});updateSliceBtns();renderActiveMeta()}
function overlay(i,vp){const v=st.viewports[i];if(!v||!v.stack)return;const ww=vp&&vp.voi?Math.round(vp.voi.windowWidth||0):'-';const wc=vp&&vp.voi?Math.round(vp.voi.windowCenter||0):'-';v.ov.innerHTML='<span>'+esc(v.label||'Series')+' '+(v.stack.currentImageIdIndex+1)+'/'+v.stack.imageIds.length+'</span><span>WW '+ww+' / WC '+wc+'</span>'}
function updateSliceBtns(){const v=st.viewports[st.active];if(!v||!v.stack||!v.stack.imageIds.length){els.prev.disabled=true;els.next.disabled=true;return}els.prev.disabled=v.stack.currentImageIdIndex<=0;els.next.disabled=v.stack.currentImageIdIndex>=v.stack.imageIds.length-1}
function renderVp(i){const v=st.viewports[i];if(!v||!v.stack||!v.stack.imageIds.length)return Promise.resolve();cornerstoneTools.clearToolState(v.el,'stack');cornerstoneTools.addToolState(v.el,'stack',v.stack);const id=v.stack.imageIds[v.stack.currentImageIdIndex];return cornerstone.loadAndCacheImage(id).then(function(img){cornerstone.displayImage(v.el,img);overlay(i,cornerstone.getViewport(v.el));if(i===st.active){renderMeta(img,v);updateSliceBtns()}}).catch(function(e){msg('Render failed: '+(e&&e.message?e.message:'Unknown'))})}
function stepSlice(d){const v=st.viewports[st.active];if(!v||!v.stack)return;const n=v.stack.currentImageIdIndex+d;if(n<0||n>=v.stack.imageIds.length)return;v.stack.currentImageIdIndex=n;renderVp(st.active)}
function buildSeries(files){const ids=files.map(function(f){return 'wadouri:'+f.url});const rows=ids.map(function(id,idx){return {id:id,file:files[idx],uid:null,num:'',desc:'',mod:'',inst:null}});let p=0;const workers=[];const max=4;
 function run(){if(p>=rows.length)return Promise.resolve();const r=rows[p++];return cornerstone.loadAndCacheImage(r.id).then(function(img){const ds=img&&img.data?img.data:null;if(ds){r.uid=ds.string('x0020000e')||null;r.num=ds.string('x00200011')||'';r.desc=ds.string('x0008103e')||'';r.mod=ds.string('x00080060')||'';const n=parseInt(ds.string('x00200013'),10);r.inst=isNaN(n)?null:n}}).catch(function(){}).then(run)}
 for(let i=0;i<Math.min(max,rows.length);i++)workers.push(run());
 return Promise.all(workers).then(function(){const map={};rows.forEach(function(r){const uid=r.uid||('path:'+(r.file.path.split('/')[0]||'default'));if(!map[uid])map[uid]={uid:uid,num:r.num||'',desc:r.desc||'',mod:r.mod||'',items:[]};map[uid].items.push(r)});const order=Object.keys(map).sort(function(a,b){const an=parseInt(map[a].num,10),bn=parseInt(map[b].num,10);if(!isNaN(an)&&!isNaN(bn)&&an!==bn)return an-bn;return a.localeCompare(b)});order.forEach(function(uid){map[uid].items.sort(function(a,b){if(a.inst!==null&&b.inst!==null&&a.inst!==b.inst)return a.inst-b.inst;return String(a.file.path).localeCompare(String(b.file.path))});map[uid].imageIds=map[uid].items.map(function(it){return it.id})});return {map:map,order:order}})
}
function loadStudy(study, key){if(!study)return Promise.reject(new Error('Missing study id'));msg('Loading '+study+'...');return fetch('/remotepanda/api/list-study-files.php?studyint='+encodeURIComponent(study),{cache:'no-store'}).then(function(r){return r.json()}).then(function(data){if(!data.success||!Array.isArray(data.files)||!data.files.length)throw new Error(data.error||'No DICOM files');msg('Parsing headers for '+data.files.length+' images...');return buildSeries(data.files).then(function(b){st.studies[key]={studyint:study,files:data.files,count:data.files.length,seriesMap:b.map,seriesOrder:b.order};if(st.order.indexOf(key)===-1)st.order.push(key);renderSeriesList();if(key==='primary')els.vmeta.textContent='Study: '+study+' | Images: '+data.files.length;msg('Loaded '+study);return st.studies[key]})})}
function renderSeriesList(){els.series.innerHTML='';st.order.forEach(function(k){const s=st.studies[k];if(!s)return;const t=document.createElement('div');t.className='series-title';t.textContent=(k==='prior'?'Prior Study':'Current Study');els.series.appendChild(t);s.seriesOrder.forEach(function(uid){const x=s.seriesMap[uid];const d=document.createElement('div');d.className='series';d.dataset.key=k;d.dataset.uid=uid;const label=(x.num?('Series '+x.num+': '):'Series: ')+(x.desc||uid.slice(0,12));d.innerHTML='<div class="a">'+esc(label)+'</div><div class="b">Images: '+x.imageIds.length+' | '+esc(x.mod||'-')+'</div>';d.addEventListener('click',function(){loadSeries(k,uid)});els.series.appendChild(d)})})}
function markSeries(k,uid){[].slice.call(els.series.querySelectorAll('.series')).forEach(function(n){n.classList.toggle('active',n.dataset.key===k&&n.dataset.uid===uid)})}
function loadSeries(k,uid){const s=st.studies[k];if(!s||!s.seriesMap[uid])return;const x=s.seriesMap[uid];const v=st.viewports[st.active];if(!v)return;v.stack={currentImageIdIndex:0,imageIds:x.imageIds.slice()};v.study=k;v.uid=uid;v.label=(x.num?('S'+x.num+' '):'')+(x.desc||uid.slice(0,8));markSeries(k,uid);renderVp(st.active)}
function compareStudies(){const a=st.studies.primary,b=st.studies.prior;if(!a||!b||!a.seriesOrder.length||!b.seriesOrder.length)return;els.layout.value='2';applyLayout(2);st.active=0;setActive(0);loadSeries('primary',a.seriesOrder[0]);st.active=1;setActive(1);loadSeries('prior',b.seriesOrder[0]);st.active=0;setActive(0)}
function renderMeta(img,v){const ds=img&&img.data?img.data:null;const o=cornerstone.getViewport(v.el);const ww=o&&o.voi?Math.round(o.voi.windowWidth||0):'-';const wc=o&&o.voi?Math.round(o.voi.windowCenter||0):'-';const rows=[['Study ID',v.study==='prior'?st.prior:st.primary],['Patient',ds?ds.string('x00100010')||'-':'-'],['Patient ID',ds?ds.string('x00100020')||'-':'-'],['Accession',ds?ds.string('x00080050')||'-':'-'],['Study Date',ds?ds.string('x00080020')||'-':'-'],['Modality',ds?ds.string('x00080060')||'-':'-'],['Study Desc',ds?ds.string('x00081030')||'-':'-'],['Series Desc',ds?ds.string('x0008103e')||'-':'-'],['Instance',ds?ds.string('x00200013')||'-':'-'],['WW/WC',ww+' / '+wc]];els.meta.innerHTML=rows.map(function(r){return '<div class="meta-row"><div class="k">'+esc(r[0])+'</div><div class="v">'+esc(r[1])+'</div></div>'}).join('')}
function renderActiveMeta(){const v=st.viewports[st.active];if(!v||!v.stack||!v.stack.imageIds.length){els.meta.innerHTML='<div class="meta-row"><div class="k">Info</div><div class="v">No image loaded.</div></div>';return}cornerstone.loadAndCacheImage(v.stack.imageIds[v.stack.currentImageIdIndex]).then(function(img){renderMeta(img,v)}).catch(function(){els.meta.innerHTML='<div class="meta-row"><div class="k">Info</div><div class="v">Metadata unavailable.</div></div>'})}
function loadNotes(){if(!st.primary)return;els.notesStatus.textContent='Loading notes...';fetch('/remotepanda/api/study-notes.php?studyint='+encodeURIComponent(st.primary),{cache:'no-store'}).then(function(r){return r.json()}).then(function(d){if(!d.success)throw new Error(d.error||'Failed');els.notes.value=d.notes||'';els.notesStatus.textContent=els.notes.value?'Notes loaded.':'No saved notes yet.'}).catch(function(e){els.notesStatus.textContent='Load failed: '+(e&&e.message?e.message:'Unknown')})}
function saveNotes(){if(!st.primary)return;els.notesStatus.textContent='Saving notes...';fetch('/remotepanda/api/study-notes.php',{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({studyint:st.primary,notes:els.notes.value||''})}).then(function(r){return r.json()}).then(function(d){if(!d.success)throw new Error(d.error||'Failed');els.notesStatus.textContent='Notes saved at '+new Date().toLocaleTimeString()}).catch(function(e){els.notesStatus.textContent='Save failed: '+(e&&e.message?e.message:'Unknown')})}
function bind(){tools.forEach(function(b){b.addEventListener('click',function(){setTool(b.dataset.tool)})});els.layout.addEventListener('change',function(){applyLayout(els.layout.value)});els.prev.addEventListener('click',function(){stepSlice(-1)});els.next.addEventListener('click',function(){stepSlice(1)});els.reset.addEventListener('click',function(){const v=st.viewports[st.active];if(!v||!v.stack)return;cornerstone.reset(v.el);renderVp(st.active)});els.priorLoad.addEventListener('click',function(){const sid=(els.priorInput.value||'').trim();if(!sid){msg('Enter prior study ID first');return}st.prior=sid;loadStudy(sid,'prior').then(function(){els.compare.disabled=false;msg('Prior loaded, click Compare')}).catch(function(e){msg('Failed prior load: '+(e&&e.message?e.message:'Unknown'))})});els.compare.addEventListener('click',compareStudies);els.notesLoad.addEventListener('click',loadNotes);els.notesSave.addEventListener('click',saveNotes);els.notesClear.addEventListener('click',function(){els.notes.value='';els.notesStatus.textContent='Cleared (not saved).'});window.addEventListener('resize',function(){st.viewports.forEach(function(v){try{cornerstone.resize(v.el,true)}catch(e){}})})}
function boot(){if(!st.primary){msg('Missing study identifier');return}if(!setup())return;bind();applyLayout(1);loadStudy(st.primary,'primary').then(function(s){if(!s.seriesOrder.length)throw new Error('No series found');loadSeries('primary',s.seriesOrder[0]);loadNotes();if(st.prior){els.priorInput.value=st.prior;return loadStudy(st.prior,'prior').then(function(){els.compare.disabled=false})}}).catch(function(e){msg('Viewer failed: '+(e&&e.message?e.message:'Unknown'))})}
boot();
})();

